### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VicDeo** [VicDeo/go-obfuscate#1]
1. [x] Compare table count in config vs DB table count, show missing/extra
2. [x] Documentation
3. [x] validate  faked types in the obfuscate section
4. [ ] validate  obfuscate section columns for  existence in DB tables
5. [ ] verbose mode (print masked tables)
